apiVersion: apps/v1
kind: Deployment
metadata: ##
  name: etd-app
  # namespace: etd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: etd-app
  template:
    metadata:
      labels:
        app: etd-app
    spec:
      containers:
        - name: etd-app
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
