apiVersion: apps/v1
kind: Deployment
metadata:
  name: etd-app
  namespace: etd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: etd-app
  template:
    metadata:
      labels:
        app: etd-app
    spec:
      containers:
        - name: etd-app
          image: 992382830946.dkr.ecr.ap-northeast-2.amazonaws.com/easy-to-dedicate
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred

